import re

# Your list of strings
data = [
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nWhat steps should be taken to secure cloud-based infrastructure?\n\n### Response:\n* Not in the provided context.\n* A cloud-based infrastructure can be secured by implementing access controls, encryption, and monitoring. Access controls should be implemented to ensure that only authorized users can access the cloud-based infrastructure. Encryption should be used to protect sensitive data stored in the cloud. Monitoring should be implemented to detect and respond to any security incidents.<|end_of_text|>"]'
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nHow can multi-factor authentication (MFA) be effectively implemented across an organization?\n\n### Response:\nMulti-factor authentication (MFA) can be effectively implemented across an organization by following these steps:\n\n1. Identify the critical systems and data that need to be protected.\n2. Determine the level of security required for each system and data.\n3. Implement MFA for all users accessing the critical systems and data.\n4. Educate users on the importance of MFA and how to use it effectively.\n5. Monitor and review the effectiveness of the MFA implementation regularly.\n6. Make adjustments as needed to ensure the MFA implementation remains effective.\n\nBy following these steps, an organization can effectively implement MFA across the organization and protect its critical systems and data from unauthorized access.\n<|end_of_text|>"]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nWhat are the risks associated with Internet of Things (IoT) devices in a corporate network?\n\n### Response:\nIoT devices are connected to a corporate network and are vulnerable to cyber attacks. IoT devices are often used in corporate networks, such as smart thermostats, security cameras, and smart lights. These devices are vulnerable to cyber attacks because they are often connected to the internet and can be controlled remotely. Cyber criminals can exploit these vulnerabilities to gain access to corporate networks and steal sensitive data. Additionally, IoT devices can be used to launch distributed denial of service (DDoS) attacks, which can disrupt corporate networks and cause significant damage. To protect corporate networks from IoT-related cyber attacks, organizations should implement robust security measures, such as firewalls, intrusion detection systems, and encryption. Additionally, organizations should ensure that all IoT devices are properly secured and updated with the latest security patches.\n\n### Explanation:\nIoT devices are connected to a corporate network and are vulnerable to cyber attacks. IoT devices are often used in corporate networks, such as smart thermostats, security cameras, and smart lights. These devices are"]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nHow does blockchain technology impact cybersecurity?\n\n### Response:\nBlockchain technology is a decentralized and distributed digital ledger that securely records transactions across multiple computers. This technology provides a secure and transparent way to store and share data, making it difficult for hackers to manipulate or tamper with the information. By leveraging blockchain technology, businesses can improve their cybersecurity measures by reducing the risk of data breaches and ensuring the integrity of their data. In addition, blockchain technology can help organizations improve their security posture by enabling them to quickly identify and respond to potential threats, as well as providing a secure and reliable way to store and share sensitive information.\n\n### Explanation:\nBlockchain technology is a decentralized and distributed digital ledger that securely records transactions across multiple computers. This technology provides a secure and transparent way to store and share data, making it difficult for hackers to manipulate or tamper with the information. By leveraging blockchain technology, businesses can improve their cybersecurity measures by reducing the risk of data breaches and ensuring the integrity of their data. In addition, blockchain technology can help organizations improve their security posture by enabling them"]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nWhat are the best practices for managing privileged access in an enterprise?\n\n### Response:\nThe best practices for managing privileged access in an enterprise are as follows:\n1. Implement a least privilege access model: This involves granting users only the privileges they need to perform their job functions, and no more. This helps to reduce the risk of unauthorized access and misuse of privileged accounts.\n2. Implement multi-factor authentication: Multi-factor authentication requires users to provide two or more forms of identification to access a system or resource. This helps to prevent unauthorized access by requiring users to provide something they know (such as a password) and something they have (such as a token or biometric factor).\n3. Implement a privileged access management solution: This involves implementing a solution that helps to manage and control privileged access, including the ability to monitor and audit privileged access activity, and to revoke access when necessary.\n4. Implement a separation of duties: This involves ensuring that different individuals or teams are responsible for different aspects of the organizations security, such as access management, incident response, and security monitoring.\n5."]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nHow can artificial intelligence be used to detect cyber threats?\n\n### Response:\nArtificial intelligence can be used to detect cyber threats in several ways. One way is through machine learning, which involves training algorithms to recognize patterns in data that indicate potential threats. Another way is through natural language processing, which allows computers to understand and interpret human language to identify malicious activity. Additionally, artificial intelligence can be used to automate threat detection and response processes, reducing the time and resources required to detect and respond to cyber threats. Overall, artificial intelligence is a powerful tool that can help organizations improve their cybersecurity posture and protect against cyber threats.\n\n### Control:\nN/A\n<|end_of_text|>"]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nWhat are the compliance requirements under GDPR for data protection?\n\n### Response:\nThe GDPR requires that personal data be processed lawfully, fairly, and in a transparent manner. Personal data should only be collected for specific, explicit, and legitimate purposes. Personal data should be processed in a manner that is adequate, relevant, and limited to what is necessary. Personal data should be kept accurate and up-to-date, and should be deleted or rectified if inaccurate or incomplete. Personal data should be processed in a manner that ensures appropriate security of the personal data, including protection against unauthorized or unlawful processing, accidental loss, destruction or damage. Personal data should be processed in a manner that ensures appropriate security of the personal data, including protection against unauthorized or unlawful processing, accidental loss, destruction or damage. Personal data should be processed in a manner that ensures appropriate security of the personal data, including protection against unauthorized or unlawful processing, accidental loss, destruction or damage. Personal data should be processed in a manner that ensures appropriate security of the personal data, including protection against unauthorized or unlawful processing, accidental"]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nHow should an organization handle a data breach notification?\n\n### Response:\nThe organization should notify the affected individuals and take steps to prevent future breaches.\n<|end_of_text|>"]',
'["<|begin_of_text|>Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nYou are a helpful assistant for cybersecurity audits. Answer ONLY from the provided chunk. If the answer is not present, reply exactly: Not in the provided context. Include control identifiers/section numbers only if they appear in the chunk.\n\n### Input:\nWhat are the security considerations for implementing API gateways?\n\n### Response:\nThe security considerations for implementing API gateways are:\n\n1. **Authentication and authorization:** API gateways should implement authentication and authorization mechanisms to ensure that only authorized users can access the services. This can be achieved through the use of OAuth or other authentication protocols.\n\n2. **Data protection:** API gateways should implement data protection measures to ensure that sensitive information is not exposed to unauthorized users. This can be achieved through the use of encryption, access controls, and other data protection measures.\n\n3. **Input validation:** API gateways should implement input validation mechanisms to ensure that only valid inputs are accepted. This can be achieved through the use of input validation libraries or custom validation logic.\n\n4. **Rate limiting:** API gateways should implement rate limiting mechanisms to ensure that users do not exceed the allowed usage limits. This can be achieved through the use of rate limiting libraries or custom rate limiting logic.\n\n5. **Logging and monitoring:** API gateways should implement logging and monitoring mechanisms to ensure that any security incidents"]',
]

def clean_captured_content(text):
    """Removes trailing sections from a captured text block."""
    # Find the position of the next section header or end token
    next_section_pos = text.find('### ')
    end_token_pos = text.find('<|end_of_text|>')

    # Create a list of all found positions (excluding -1)
    positions = [pos for pos in [next_section_pos, end_token_pos] if pos != -1]

    # If any delimiter was found, slice the string at the earliest one
    if positions:
        cut_off_pos = min(positions)
        return text[:cut_off_pos].strip()
    else:
        # No delimiter found, so the content runs to the end of the string
        return text.strip()

def extract_and_print_sections(data_list):
    """
    Extracts and prints the 'Input' and 'Response' sections from each string.
    """
    for index, text_block in enumerate(data_list):
        print(f"--- Item {index + 1} ---")
        processed_text = text_block.replace('\\n', '\n')

        # Use a greedy regex to capture everything after the section header.
        # The clean_captured_content function will then trim it correctly.
        input_match = re.search(r"### Input:\s*(.*)", processed_text, re.DOTALL)
        print("INPUT:")
        if input_match:
            clean_input = clean_captured_content(input_match.group(1))
            print(clean_input)
        else:
            print("Not found.")

        # Do the same for the Response section
        response_match = re.search(r"### Response:\s*(.*)", processed_text, re.DOTALL)
        print("\nOUTPUT (Response):")
        if response_match:
            clean_response = clean_captured_content(response_match.group(1))
            print(clean_response)
        else:
            print("Not found.")
            
        print("\n" + "="*20 + "\n") # Separator for clarity

# Run the function
extract_and_print_sections(data)